CREATE TABLE CONSUMER(
CONSUMERID INT,
PHONE VARCHAR(15),
NAME VARCHAR(20),
ADDRESS VARCHAR(30),
AGE INT,
PRIMARY KEY(CONSUMERID)
);

CREATE TABLE FARMER(
FARMERID INT,
PHONE VARCHAR(15),
NAME VARCHAR(20),
ADDRESS VARCHAR(30),
BIRTH DATE,
EMAIL VARCHAR(20),
PRIMARY KEY(FARMERID)
);

CREATE TABLE FARM(
FARMID INT,
NAME VARCHAR(20),
ADDRESS VARCHAR(30),
IFPLANT BOOL,
IFANIMAL BOOL,
IFBOTH BOOL,
PRIMARY KEY(FARMID),
);

CREATE TABLE ANIMAL(
ANIMALSCNAME VARCHAR(30),
NAME VARCHAR(20),
PRICE DOUBLE,
AMOUNTSALE DOUBLE,
AMOUNT INT,
UNIT VARCHAR(20),
PRIMARY KEY(ANIMALSCNAME),
);

CREATE TABLE PLANT(ER(
PLANTSCNAME VARCHAR(30),
NAME VARCHAR(20),
PRICE DOUBLE,
AMOUNTSALE DOUBLE,
AMOUNT INT,
UNIT VARCHAR(20),
PRIMARY KEY(PLANTSCNAME),
);

CREATE TABLE CART(
CUSTCARTID INT,
ANIMALSCNAME VARCHAR(20),
PLANTSCNAME VARCHAR(20),
PRIMARY KEY(CUSTCARTID),
);


CREATE TABLE ONSALECART(
CARTID INT,
ANIMALSCNAME VARCHAR(20),
PLANTSCNAME VARCHAR(20),
PRIMARY KEY(CARTID),
);
