CREATE TABLE CONSUMER(
CONSUMERID INT,
PHONE VARCHAR(15),
NAME VARCHAR(20),
ADDRESS VARCHAR(30),
AGE INT,
PRIMARY KEY(CONSUMERID)
);

CREATE TABLE FARMER(
FARMERID INT,
PHONE VARCHAR(15),
NAME VARCHAR(20),
ADDRESS VARCHAR(30),
BIRTH DATE,
EMAIL VARCHAR(20),
PRIMARY KEY(FARMERID)
);

CREATE TABLE FARM(
FARMID INT,
FARMERID INT,
NAME VARCHAR(20),
ADDRESS VARCHAR(30),
IFPLANT BOOL,
IFANIMAL BOOL,
IFBOTH BOOL,
PRIMARY KEY(FARMID, FARMERID),
FOREIGN KEY(FARMERID)
    REFERENCES FARMER(FARMERID)
);

CREATE TABLE ANIMAL(
FARMID INT,
ANIMALSCNAME VARCHAR(30),
NAME VARCHAR(20),
PRICE DOUBLE,
AMOUNTSALE DOUBLE,
AMOUNT INT,
UNIT VARCHAR(20),
PRIMARY KEY(ANIMALSCNAME, FARMID),
FOREIGN KEY(FARMID)
    REFERENCES FARM(FARMID)
);

CREATE TABLE PLANT(
FARMID INT,
PLANTSCNAME VARCHAR(30),
NAME VARCHAR(20),
PRICE DOUBLE,
AMOUNTSALE DOUBLE,
AMOUNT INT,
UNIT VARCHAR(20),
PRIMARY KEY(PLANTSCNAME, FARMID),
FOREIGN KEY(FARMID)
    REFERENCES FARM(FARMID)
);

CREATE TABLE CART(
CONSUMERID INT,
CUSTCARTID INT,
ANIMALSCNAME VARCHAR(20),
PLANTSCNAME VARCHAR(20),
PRIMARY KEY(CUSTCARTID, CONSUMERID),
FOREIGN KEY(CONSUMERID)
        REFERENCES CONSUMER(CONSUMERID)
);


CREATE TABLE ONSALECART(
FARMID INT,     
CARTID INT,
ANIMALSCNAME VARCHAR(20),
PLANTSCNAME VARCHAR(20),
PRIMARY KEY(CARTID,FARMID),
FOREIGN KEY(FARMID)
        REFERENCES FARM(FARMID)
);
