LOAD DATA LOCAL INFILE "CONSUMER.csv"
INTO TABLE CONSUMER
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CONSUMERID, PHONE, NAME, ADDRESS, AGE);

LOAD DATA LOCAL INFILE "FARMER.csv"
INTO TABLE FARMER
FIELDS TERMINATED BY ','
IGNORE 1 ROWS
(FARMERID, PHONE, NAME, ADDRESS, BIRTH, EMAIL);

LOAD DATA LOCAL INFILE "FARM.csv"
INTO TABLE FARM
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(FARMID, FARMERID, NAME, ADDRESS, IFPLANT, IFANIMAL, IFBOTH);

LOAD DATA LOCAL INFILE "ANIMAL.csv"
INTO TABLE ANIMAL
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(FARMID, ANIMALSCNAME, NAME, PRICE, AMOUNTSALE, AMOUNT, UNIT, CONDITION);

LOAD DATA LOCAL INFILE "PLANT.csv"
INTO TABLE PLANT
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(FARMID, PLANTSCNAME, NAME, PRICE, AMOUNTSALE, AMOUNT, UNIT, CONDITION);

LOAD DATA LOCAL INFILE "CART.csv"
INTO TABLE CART
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CONSUMERID, CUSTCARTID, ANIMALSCNAME, PLANTSCNAME);

LOAD DATA LOCAL INFILE "ONSALECART.csv"
INTO TABLE ONSALECART
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CARTID, FARMID, ANIMALSCNAME, PLANTSCNAME);